// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_ZrB8TXsxt",
    "aws_user_pools_web_client_id": "2a687782li4fg9nubhqd55q9o",
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "games",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
